# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project.
  Yolov3 is an algorithm that uses convolutional neural network to perform object detection. Open source two endpoints each for image and video detections which can be integrate in any application. An example of integration with iOS app is shown in this repo.
  Please adhere to our [Code of Conduct](https://github.com/Akashsindhu/AIes_object_detection/blob/master/CODE_OF_CONDUCT.md).
  Please make sure not to start working on the issue, unless you get assigned to it.ğŸ˜„
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  Thank you and congratsğŸ‰ for opening your first pull request. 
  Yolov3 is an algorithm that uses convolutional neural network to perform object detection. Open source two endpoints each for image and video detections which can be integrate in any application. An example of integration with iOS app is shown in this repo.
  Please make sure you have followed our contributing guidlines .ğŸ™ŒğŸ™Œ We will get back to you as soon as we can ğŸ˜„.
  
 
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on getting your  first pull request merged! ğŸ‰ All the best for your amazing open source journey ahead ğŸš€.
  
